import { Inter } from "next/font/google";
import Header from "@/components/Header";
import SessionWraper from "@/components/SessionWraper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWraper>
      <html lang="en">
        <body className={inter.className}>{children}
        <Header />
        </body>
        
      </html>
    </SessionWraper>
  );
}
